name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up directories
      run: mkdir obj lib bin

    - name: Clean build
      run: make again

    - name: Unit test
      run: make check
